### ISSUE TITLE
Question about reparametrization and number of parameters

### ISSUE THREAD

**Issue by stephandooper** [AIH-SGML/MixMIL#6]
Hi, thank you for providing the materials for implementing your paper.

**Reparametrization:**
I've been going over the details about the implementation in the appendix, and I was wondering about the specifics of the reparametrization introduced in section A.1: 

I was a bit puzzled about the exact details of the normalization introduced here. I understand why you would want the sample variance to equal the sum of squared $\beta$ so that it is linked to explained variance, but I don't quite understand the derivation. 

First, what does it mean that $\eta$ in A.2 has unit mean square? I assumed that it meant $\mathbb{E}[\eta^2]$ = 1, but I don't quite see how that is achieved with the rescaling.

Secondly, why do we need this rescaling with $\eta$ in the normalization formula A.3 instead of normalizing using just the regular formula for $u$?. I.e., why can't we do this:

$$u = b \times \frac{u - mean(u)}{ std(u)}$$
instead of 

$$u = b \times \frac{\widetilde{u} - mean(\widetilde{u})}{ std(\widetilde{u})}$$

is there a more lengthy explanation somewhere that I can follow?

**Number of parameters**
In the paper it was explained that there are a total of $2Q + Q(2Q+1)$ variational parameters, assuming full rank, and $2Q + K$ likelilhood parameters. I understand where the number of variational parameters are coming from, but what exactly comprises the likelihood parameters? Is it $2Q$ parameters coming from $\beta$ and $\gamma$, respectively, and $K$ parameters coming from $\alpha$? Are the trainable parameters from $\sigma_{\beta}$ and $\sigma_{\gamma}$ also included somewhere within the numbers of likelihood/variational parameters?

![image](https://github.com/AIH-SGML/mixmil/assets/31624652/22092fa4-7a41-4e77-b81f-4b8575de346f)

**Comment by jan-engelmann** [comment]
Hi Stephan,

thank you for your questions!

> First, what does it mean that  $\eta$ in A.2 has unit mean square? 

It means:
$$\frac{1}{Q} \sum_{i}^Q  \eta_{i}^2= 1$$

> why can't we do this:
> 
> $$u = b \times \frac{u - mean(u)}{ std(u)}$$
> instead of 
> 
> $$u = b \times \frac{\widetilde{u} - mean(\widetilde{u})}{ std(\widetilde{u})}$$


You are right that the two formulations are mathematically equivalent. However, as we mention in the Appendix we found our reparametrization to increase numerical stability.

> … but what exactly comprises the likelihood parameters? Is it $2Q$ parameters coming from $\beta$ and $\gamma$, respectively, and $K$ parameters coming from $\alpha$? 

Exactly! Q parameters from $\beta$, Q from $\gamma$, and $K$ from $\alpha$. We get $\beta$ and $\gamma$ by sampling from the variational posterior.

> Are the trainable parameters from $\sigma_{\beta}$ and $\sigma_{\gamma}$ also included somewhere within the numbers of likelihood/variational parameters?

No, they are not counted since they are prior hyperparameters. Please note that $\sigma_{\beta}$ and $\sigma_{\gamma}$  are both single numbers for the regression case.

I hope this answers your questions! Feel free to reopen if not.

Cheers,
Jan
